- name: Set overcommit sysctl entry
  sysctl: >
    name=vm.overcommit_memory
    value=1
    sysctl_file=/etc/sysctl.d/60-redis-overcommit.conf

- name: Adds Redis config
  template: >
    src="../templates/redis.conf.j2"
    dest=/etc/redis/redis.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify:
    - Restart redis
